routes/web.php
<?php
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('histories', 'App\Http\Controllers\HistoriesController');

app/Models/Histories.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Histories extends Model
{
    use HasFactory;
    protected $fillable = ['title', 'description', 'user_name'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HistoriesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateHistoriesRequest;
use App\Http\Requests\EditHistoriesRequest;
use App\Models\Histories;
use Illuminate\Http\Request;


class HistoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $histories = Histories::paginate(10);
        return view('histories.index', compact('histories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('histories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateHistoriesRequest $request)
    {
        Histories::create([
            'title' => $request->title,
            'description' => $request->description,
            'user_name' => $request->user_name
        ]);

        flash("Histories created successfully");
        return redirect()->route('histories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Histories  $histories
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $histories = Histories::findOrFail($id);
        // $histories = Histories::all();
        return view('histories.show', compact('histories'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Histories  $histories
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $histories = Histories::findOrFail($id);
        return view('histories.edit', compact('histories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Histories  $histories
     * @return \Illuminate\Http\Response
     */
    public function update(EditHistoriesRequest $request, Histories $histories, $id)
    {
        $validatedData = $request->validate([
           'title' => 'required|max:255',
           'description' => 'required',
           'user_name' => 'required'
        ]);
        Histories::whereId($id)->update($validatedData);

       return redirect('/histories')->with('success', 'Histories Data is successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Histories  $histories
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $histories = Histories::findOrFail($id);
        $histories->delete();
        flash("Histories Deleted Successfully");
        return redirect()->back();
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/histories/create.blade.php
@extends('layouts.master')

@section('title') Create Histories @endsection

@section('content')
    <form action="{{ route('histories.store') }}" method="post">
        @csrf
        <div class="card card-default">
            <div class="card-header">
                Create Histories
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" class="form-control @if($errors->has('title')) is-invalid @endif" name="title" value="{{ old('title') }}">
                    @if($errors->has('title'))
                        <div class="invalid-feedback">{{ $errors->first('title') }}</div>
                    @endif
                </div>
                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea cols="5" rows="3" class="form-control @if($errors->has('description')) is-invalid @endif" name="description">{{ ('') }}</textarea>
                    @if($errors->has('description'))
                        <div class="invalid-feedback">{{ $errors->first('description') }}</div>
                    @endif
                </div>
                <div class="form-group">
                    <label for="user_name">User name</label>
                    <input type="text" class="form-control @if($errors->has('user_name')) is-invalid @endif" name="user_name" value="{{ old('user_name') }}">
                    @if($errors->has('user_name'))
                        <div class="invalid-feedback">{{ $errors->first('user_name') }}</div>
                    @endif
                </div>
            </div>
            <div class="card-footer">
                <button class="btn btn-primary" type="submit">Save</button>
                <a href="{{ route('histories.index') }}" class="btn btn-default">Cancel</a>
            </div>
        </div>
    </form>
@endsection

resources/views/histories/edit.blade.php
@extends('layouts.master')

@section('title') Edit Histories @endsection

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Edit Histories
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('histories.update', $histories->id ) }}">
          <div class="form-group">
              @csrf
              @method('PATCH')
              <label for="title">Title</label>
              <input type="text" class="form-control" name="title" value="{{ $histories->title }}"/>
          </div>
          <div class="form-group">
              <label for="description">Description</label>
              <input type="text" class="form-control" name="description" value="{{ $histories->description }}"/>
          </div>
          <div class="form-group">
              <label for="user_name">User Name</label>
              <input type="text" class="form-control" name="user_name" value="{{ $histories->user_name }}"/>
          </div>
          <button type="submit" class="btn btn-primary">Update</button>
          <a href="http://localhost:8000/histories" class="btn btn-default">Cancel</a>
      </form>
  </div>
</div>
@endsection

resources/views/histories/index.blade.php
@extends('layouts.master')

@section('title') Histories @endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <a href="{{ route('histories.create') }}" class="btn btn-primary pull-right mb-3">Add New</a>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Title</th>
                <th>Description</th>
                <th>User Name</th>
                <th>Updated At</th>
                <th>Created At</th>
            </tr>
            </thead>
            <tbody>
            @forelse($histories as $histori)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $histori->title }}</td>
                    <td>{{ $histori->description }}</td>
                    <td>{{ $histori->user_name }}</td>
                    <td>{{ $histori->updated_at->diffForHumans() }}</td>
                    <td>{{ $histori->created_at->diffForHumans() }}</td>
                    <td>
                        <div class="btn-group" role="group" aria-label="Basic example">
                            <a href="{{ route('histories.edit', $histori->id)}}" type="button" class="btn btn-primary"><i class="fa fa-edit"></i></a>
                            <a href="{{ route('histories.show', $histori->id) }}" type="button" class="btn btn-info"><i class="fa fa-eye"></i></a>

                            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete_histori_{{ $histori->id }}">
                                <i class="fa fa-trash"></i>
                            </button>

                            <div class="modal fade" id="delete_histori_{{ $histori->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <form action="{{ route('histories.destroy', $histori->id) }}" id="form_delete_histori_{{ $histori->id }}" method="post">
                                        @csrf
                                        @method('DELETE');
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Delete Confirmation</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">×</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                Are you sure want to delete "<b>{{ $histori->title }}</b>" histori?
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                                                <button type="submit" class="btn btn-danger">Yes! Delete It</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" align="center">No Histories Found.</td>
                </tr>
            @endforelse
            </tbody>
        </table>
    </div>
    <div class="row">
        {{ $histories->links() }}
    </div>
@endsection

resources/views/histories/show.blade.php
@extends('layouts.master')

@section('title') View Histories @endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <a href="{{ route('histories.index') }}" class="btn btn-info pull-right mb-3">Back</a>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-striped">
            <tr>
                <th>Title</th>
                <td>{{ $histories->title }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ $histories->description }}</td>
            </tr>
            <tr>
                <th>User Name</th>
                <td>{{ $histories->user_name }}</td>
            </tr>
            <tr>
                <th>Updated At</th>
                <td>{{ $histories->updated_at->diffForHumans() }}</td>
            </tr>
            <tr>
                <th>Created At</th>
                <td>{{ $histories->created_at->diffForHumans() }}</td>
            </tr>
        </table>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title', env('APP_NAME'))</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

<div class="container my-5">
    @include('flash::message')
    @yield('content')
</div>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script>
    $('div.alert').not('.alert-important').delay(3000).fadeOut(350);
</script>
</body>
</html>